/* ══════════════════════════════════════════
   Travel Destination Database (100+)
   ══════════════════════════════════════════ */

export type TravelStyle = "힐링" | "액티비티" | "문화탐방" | "맛집투어" | "자연" | "쇼핑";
export type Companion = "혼자" | "연인" | "친구" | "가족(아이)" | "부모님";
export type Season = "봄" | "여름" | "가을" | "겨울";
export type Duration = "당일치기" | "1박2일" | "2박3일" | "일주일 이상";
export type Budget = "~10만원" | "~30만원" | "~50만원" | "~100만원" | "100만원 이상";
export type Region = "국내" | "해외(가까운)" | "해외(먼)";
export type Dislike = "비행기" | "더위" | "추위" | "등산" | "바다";

export interface Destination {
  name: string;
  emoji: string;
  region: Region;
  country: string;
  description: string;
  bestSeasons: Season[];
  durations: Duration[];
  budgetLevel: number; // 1~5
  styles: TravelStyle[];
  companions: Companion[];
  highlights: string[];
  tip: string;
  dislikeFlags?: Dislike[];
}

export const STYLES: TravelStyle[] = ["힐링", "액티비티", "문화탐방", "맛집투어", "자연", "쇼핑"];
export const COMPANIONS: Companion[] = ["혼자", "연인", "친구", "가족(아이)", "부모님"];
export const SEASONS: Season[] = ["봄", "여름", "가을", "겨울"];
export const DURATIONS: Duration[] = ["당일치기", "1박2일", "2박3일", "일주일 이상"];
export const BUDGETS: Budget[] = ["~10만원", "~30만원", "~50만원", "~100만원", "100만원 이상"];
export const REGIONS: Region[] = ["국내", "해외(가까운)", "해외(먼)"];
export const DISLIKES: Dislike[] = ["비행기", "더위", "추위", "등산", "바다"];

export const BUDGET_LEVEL: Record<Budget, number> = {
  "~10만원": 1,
  "~30만원": 2,
  "~50만원": 3,
  "~100만원": 4,
  "100만원 이상": 5,
};

const D: Destination[] = [
  // ═══ 국내 (65) ═══
  { name: "제주도", emoji: "🍊", region: "국내", country: "대한민국", description: "한라산과 아름다운 해변, 독특한 문화가 어우러진 섬", bestSeasons: ["봄", "여름", "가을"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["힐링", "자연", "맛집투어", "액티비티"], companions: ["연인", "친구", "가족(아이)", "혼자"], highlights: ["한라산 등반", "성산일출봉", "흑돼지 맛집", "카페 투어"], tip: "렌터카가 필수입니다. 동쪽과 서쪽을 나눠서 일정을 짜면 효율적이에요.", dislikeFlags: ["바다"] },
  { name: "부산", emoji: "🌊", region: "국내", country: "대한민국", description: "해운대 해변과 맛집의 도시", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["맛집투어", "힐링", "문화탐방", "쇼핑"], companions: ["연인", "친구", "가족(아이)", "혼자", "부모님"], highlights: ["해운대 해변", "감천문화마을", "자갈치시장", "광안대교 야경"], tip: "KTX로 2시간 30분이면 도착! 지하철이 잘 되어 있어 대중교통 여행이 편리해요.", dislikeFlags: ["바다"] },
  { name: "강릉", emoji: "☕", region: "국내", country: "대한민국", description: "커피와 바다의 도시, 강원도의 보석", bestSeasons: ["봄", "여름", "가을", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["힐링", "맛집투어", "자연"], companions: ["연인", "친구", "혼자", "부모님"], highlights: ["안목해변 카페거리", "경포대", "초당 순두부", "오죽헌"], tip: "KTX 강릉선으로 서울에서 2시간! 안목해변 카페거리는 꼭 가보세요.", dislikeFlags: ["바다"] },
  { name: "경주", emoji: "🏛️", region: "국내", country: "대한민국", description: "천년 고도, 신라의 역사가 살아 숨쉬는 도시", bestSeasons: ["봄", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["문화탐방", "힐링", "맛집투어"], companions: ["연인", "가족(아이)", "부모님", "혼자", "친구"], highlights: ["불국사", "석굴암", "첨성대", "황리단길"], tip: "봄 벚꽃 시즌과 가을 단풍 시즌이 가장 아름다워요. 자전거 대여로 시내 관광 추천!", dislikeFlags: [] },
  { name: "여수", emoji: "🌅", region: "국내", country: "대한민국", description: "밤바다와 해상 케이블카의 낭만 도시", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["힐링", "맛집투어", "자연"], companions: ["연인", "친구", "가족(아이)", "부모님"], highlights: ["여수 밤바다", "해상 케이블카", "돌산대교", "갓김치·게장 맛집"], tip: "여수 밤바다 뷰 숙소를 미리 예약하세요. 해상 케이블카 야간 탑승이 특히 로맨틱해요.", dislikeFlags: ["바다"] },
  { name: "전주", emoji: "🍚", region: "국내", country: "대한민국", description: "한옥마을과 비빔밥의 고장", bestSeasons: ["봄", "가을", "겨울"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["맛집투어", "문화탐방", "힐링"], companions: ["연인", "친구", "혼자", "가족(아이)", "부모님"], highlights: ["한옥마을", "비빔밥 맛집", "한복 체험", "막걸리 골목"], tip: "한복을 빌려 입으면 한옥마을 입장료가 무료인 곳이 많아요!", dislikeFlags: [] },
  { name: "속초", emoji: "🏔️", region: "국내", country: "대한민국", description: "설악산과 바다가 만나는 도시", bestSeasons: ["여름", "가을", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "맛집투어", "액티비티"], companions: ["친구", "연인", "가족(아이)", "혼자"], highlights: ["설악산 케이블카", "속초 중앙시장", "영금정 일출", "아바이마을"], tip: "가을 단풍 시즌에는 숙소를 최소 한 달 전에 예약하세요.", dislikeFlags: ["등산", "바다"] },
  { name: "양양", emoji: "🏄", region: "국내", country: "대한민국", description: "서핑과 자연을 즐기는 힙한 해변 마을", bestSeasons: ["여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["액티비티", "힐링", "자연"], companions: ["친구", "연인", "혼자"], highlights: ["서핑", "낙산사", "하조대", "죽도해변 카페"], tip: "서핑 초보자도 쉽게 배울 수 있는 서핑 스쿨이 많아요.", dislikeFlags: ["바다"] },
  { name: "남해", emoji: "🌿", region: "국내", country: "대한민국", description: "독일마을과 다랭이마을의 힐링 섬", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["힐링", "자연", "문화탐방"], companions: ["연인", "부모님", "가족(아이)", "혼자"], highlights: ["독일마을", "다랭이마을", "보리암 일출", "멸치쌈밥"], tip: "렌터카가 있으면 훨씬 편리해요. 보리암 일출은 꼭 보세요!", dislikeFlags: ["바다"] },
  { name: "통영", emoji: "🐙", region: "국내", country: "대한민국", description: "한국의 나폴리, 해산물과 예술의 도시", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["맛집투어", "힐링", "문화탐방", "자연"], companions: ["연인", "친구", "부모님", "가족(아이)"], highlights: ["동피랑 벽화마을", "한려수도 케이블카", "꿀빵", "충무김밥"], tip: "미륵도 일주도로 드라이브가 환상적이에요!", dislikeFlags: ["바다"] },
  { name: "담양", emoji: "🎋", region: "국내", country: "대한민국", description: "대나무 숲과 떡갈비의 고장", bestSeasons: ["봄", "여름", "가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["자연", "힐링", "맛집투어"], companions: ["연인", "부모님", "가족(아이)", "혼자", "친구"], highlights: ["죽녹원", "메타세쿼이아 가로수길", "떡갈비", "소쇄원"], tip: "메타세쿼이아 가로수길은 사계절 아름답지만 여름 초록이 가장 아름다워요.", dislikeFlags: [] },
  { name: "포항", emoji: "🌄", region: "국내", country: "대한민국", description: "일출의 도시, 과메기와 해안도로", bestSeasons: ["가을", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["맛집투어", "자연", "힐링"], companions: ["친구", "연인", "부모님", "혼자"], highlights: ["호미곶 일출", "과메기", "이가리 닻 전망대", "스페이스워크"], tip: "겨울 과메기 시즌에 방문하면 신선한 과메기를 맛볼 수 있어요.", dislikeFlags: ["바다"] },
  { name: "안동", emoji: "🏡", region: "국내", country: "대한민국", description: "유교 문화의 중심, 하회마을의 도시", bestSeasons: ["봄", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["부모님", "연인", "혼자", "가족(아이)"], highlights: ["하회마을", "안동찜닭", "월영교", "도산서원"], tip: "하회마을은 하루를 투자해서 천천히 둘러보세요. 탈춤 공연도 볼 수 있어요.", dislikeFlags: [] },
  { name: "춘천", emoji: "🍗", region: "국내", country: "대한민국", description: "닭갈비와 남이섬의 낭만 도시", bestSeasons: ["봄", "가을", "겨울"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["맛집투어", "자연", "힐링"], companions: ["연인", "친구", "가족(아이)", "혼자"], highlights: ["남이섬", "닭갈비 골목", "소양강 스카이워크", "제이드가든"], tip: "ITX 청춘열차로 서울에서 1시간 20분! 당일치기로도 좋아요.", dislikeFlags: [] },
  { name: "가평", emoji: "🌲", region: "국내", country: "대한민국", description: "서울 근교 자연 속 힐링 여행지", bestSeasons: ["봄", "여름", "가을", "겨울"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["자연", "힐링", "액티비티"], companions: ["연인", "가족(아이)", "친구", "혼자"], highlights: ["자라섬", "쁘띠프랑스", "아침고요수목원", "번지점프"], tip: "경춘선 기차 여행이 로맨틱해요. 계절마다 다른 매력이 있어요.", dislikeFlags: [] },
  { name: "인천", emoji: "🏝️", region: "국내", country: "대한민국", description: "차이나타운과 섬 여행의 관문", bestSeasons: ["봄", "여름", "가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["맛집투어", "문화탐방", "쇼핑"], companions: ["연인", "친구", "가족(아이)", "혼자"], highlights: ["차이나타운", "월미도", "을왕리 해변", "송도센트럴파크"], tip: "수도권에서 당일치기로 가기 좋아요. 짜장면 발상지도 방문해보세요!", dislikeFlags: [] },
  { name: "대구", emoji: "🌸", region: "국내", country: "대한민국", description: "팔공산과 맛집의 도시", bestSeasons: ["봄", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["맛집투어", "문화탐방", "쇼핑"], companions: ["친구", "연인", "혼자", "부모님"], highlights: ["팔공산 케이블카", "서문시장", "앞산 전망대", "동성로"], tip: "대구 막창과 납작만두는 반드시 맛보세요!", dislikeFlags: [] },
  { name: "광주", emoji: "🎨", region: "국내", country: "대한민국", description: "예술과 맛의 도시, 충장로의 활기", bestSeasons: ["봄", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["맛집투어", "문화탐방", "쇼핑"], companions: ["친구", "혼자", "연인", "부모님"], highlights: ["국립아시아문화전당", "양림동", "송정 떡갈비", "무등산"], tip: "광주 비엔날레 기간에 방문하면 다양한 현대미술 작품을 감상할 수 있어요.", dislikeFlags: [] },
  { name: "목포", emoji: "🐟", region: "국내", country: "대한민국", description: "서해안의 항구도시, 해산물의 천국", bestSeasons: ["봄", "가을", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["맛집투어", "문화탐방", "힐링"], companions: ["부모님", "연인", "친구", "혼자"], highlights: ["유달산", "목포 근대역사관", "세발낙지", "평화광장 야경"], tip: "목포는 KTX로 서울에서 2시간 30분! 낙지와 홍어가 유명해요.", dislikeFlags: ["바다"] },
  { name: "순천", emoji: "🦢", region: "국내", country: "대한민국", description: "순천만 습지와 자연생태의 보고", bestSeasons: ["봄", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "힐링", "문화탐방"], companions: ["연인", "부모님", "가족(아이)", "혼자"], highlights: ["순천만 습지", "순천만국가정원", "낙안읍성", "선암사"], tip: "순천만 습지 일몰은 꼭 보세요. 갈대밭이 황금빛으로 물드는 가을이 최고!", dislikeFlags: [] },
  { name: "태안", emoji: "🌾", region: "국내", country: "대한민국", description: "서해안 해변과 꽃지 해수욕장", bestSeasons: ["여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "힐링", "액티비티"], companions: ["가족(아이)", "연인", "친구"], highlights: ["꽃지 해수욕장 일몰", "안면도 자연휴양림", "신두리 해안사구", "대하축제"], tip: "가을 대하축제 시기에 가면 싱싱한 대하를 저렴하게 즐길 수 있어요.", dislikeFlags: ["바다"] },
  { name: "보령", emoji: "💦", region: "국내", country: "대한민국", description: "머드축제와 대천해수욕장의 도시", bestSeasons: ["여름"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["액티비티", "힐링", "자연"], companions: ["친구", "연인", "가족(아이)"], highlights: ["보령 머드축제", "대천해수욕장", "무창포 신비의 바닷길", "성주산 자연휴양림"], tip: "7월 머드축제 기간에는 전 세계 여행객이 몰려요. 숙소 미리 예약 필수!", dislikeFlags: ["바다"] },
  { name: "울릉도", emoji: "🏝️", region: "국내", country: "대한민국", description: "신비의 섬, 독도 가는 길", bestSeasons: ["여름", "가을"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["자연", "액티비티", "힐링"], companions: ["친구", "연인", "혼자"], highlights: ["독도 관광", "나리분지", "행남해안산책로", "오징어 물회"], tip: "배편이 한정적이므로 날씨를 꼭 확인하고 예약하세요.", dislikeFlags: ["바다"] },
  { name: "거제", emoji: "🌺", region: "국내", country: "대한민국", description: "외도와 바람의 언덕, 남해안의 보석", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "힐링", "문화탐방"], companions: ["연인", "가족(아이)", "부모님", "친구"], highlights: ["외도 보타니아", "바람의 언덕", "해금강", "거제 포로수용소"], tip: "외도 가는 유람선은 날씨에 따라 결항될 수 있으니 일정을 유연하게!", dislikeFlags: ["바다"] },
  { name: "하동", emoji: "🍵", region: "국내", country: "대한민국", description: "지리산 자락의 녹차밭과 섬진강", bestSeasons: ["봄", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "힐링", "맛집투어"], companions: ["연인", "부모님", "혼자"], highlights: ["쌍계사", "하동 녹차밭", "섬진강 벚꽃길", "재첩국"], tip: "봄 벚꽃 시즌에 십리벚꽃길을 드라이브하면 환상적이에요!", dislikeFlags: [] },
  { name: "영월", emoji: "⭐", region: "국내", country: "대한민국", description: "별마로천문대와 동강의 래프팅 도시", bestSeasons: ["여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "액티비티", "힐링"], companions: ["친구", "연인", "가족(아이)"], highlights: ["별마로 천문대", "동강 래프팅", "선돌", "장릉"], tip: "밤에 별마로천문대에서 보는 별이 정말 아름다워요. 사전 예약 필수!", dislikeFlags: [] },
  { name: "정선", emoji: "🎿", region: "국내", country: "대한민국", description: "레일바이크와 하이원 리조트", bestSeasons: ["여름", "가을", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["액티비티", "자연", "힐링"], companions: ["연인", "친구", "가족(아이)"], highlights: ["레일바이크", "하이원 리조트", "정선 아리랑 시장", "화암동굴"], tip: "겨울에는 하이원 스키장, 여름에는 레일바이크와 래프팅을 즐겨보세요.", dislikeFlags: [] },
  { name: "평창", emoji: "🎿", region: "국내", country: "대한민국", description: "동계올림픽의 도시, 대관령 목장", bestSeasons: ["여름", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "액티비티", "힐링"], companions: ["가족(아이)", "연인", "친구"], highlights: ["대관령 양떼목장", "알펜시아", "월정사 전나무숲길", "평창 올림픽공원"], tip: "여름에는 시원한 고원 기후로 피서지로 인기! 겨울에는 스키 여행으로 딱이에요.", dislikeFlags: [] },
  { name: "화천", emoji: "🐟", region: "국내", country: "대한민국", description: "산천어축제와 청정 자연의 고장", bestSeasons: ["여름", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "액티비티"], companions: ["가족(아이)", "친구", "연인"], highlights: ["산천어축제", "파로호", "비수구미 마을", "감성마을"], tip: "1~2월 산천어축제는 한국 대표 겨울축제! 얼음낚시를 꼭 체험해보세요.", dislikeFlags: ["추위"] },
  { name: "단양", emoji: "🚣", region: "국내", country: "대한민국", description: "충북의 알프스, 패러글라이딩과 단양팔경", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "액티비티", "힐링"], companions: ["연인", "친구", "가족(아이)"], highlights: ["만천하 스카이워크", "도담삼봉", "고수동굴", "패러글라이딩"], tip: "패러글라이딩은 날씨가 좋은 날 오전에 가는 것이 좋아요!", dislikeFlags: [] },
  { name: "공주", emoji: "🏯", region: "국내", country: "대한민국", description: "백제의 고도, 공산성과 무령왕릉", bestSeasons: ["봄", "가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["문화탐방", "힐링"], companions: ["부모님", "연인", "혼자", "가족(아이)"], highlights: ["공산성", "무령왕릉", "계룡산", "밤 축제"], tip: "가을 공주 알밤축제 때 방문하면 다양한 밤 요리를 즐길 수 있어요.", dislikeFlags: [] },
  { name: "부여", emoji: "🌸", region: "국내", country: "대한민국", description: "백제 문화의 중심, 부소산성과 궁남지", bestSeasons: ["봄", "여름", "가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["문화탐방", "힐링", "자연"], companions: ["부모님", "연인", "혼자", "가족(아이)"], highlights: ["부소산성", "궁남지 연꽃", "정림사지", "백제문화단지"], tip: "여름 궁남지 연꽃축제가 아름다워요!", dislikeFlags: [] },
  { name: "군산", emoji: "🍞", region: "국내", country: "대한민국", description: "시간여행의 도시, 근대문화유산과 빵집", bestSeasons: ["봄", "가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["연인", "친구", "혼자", "부모님"], highlights: ["이성당 빵집", "경암동 철길마을", "근대역사박물관", "새만금"], tip: "이성당은 한국에서 가장 오래된 빵집! 단팥빵과 야채빵이 유명해요.", dislikeFlags: [] },
  { name: "대전", emoji: "🔬", region: "국내", country: "대한민국", description: "과학도시, 성심당 빵과 칼국수", bestSeasons: ["봄", "가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["맛집투어", "문화탐방"], companions: ["친구", "연인", "혼자"], highlights: ["성심당", "대전 칼국수", "엑스포과학공원", "한밭수목원"], tip: "성심당 본점은 항상 줄이 기니 오전에 일찍 가세요!", dislikeFlags: [] },
  { name: "수원", emoji: "🏰", region: "국내", country: "대한민국", description: "화성과 치킨거리의 도시", bestSeasons: ["봄", "가을"], durations: ["당일치기"], budgetLevel: 1, styles: ["문화탐방", "맛집투어"], companions: ["연인", "친구", "혼자", "가족(아이)", "부모님"], highlights: ["수원화성", "통닭거리", "화성행궁", "광교호수공원"], tip: "수원화성 야간 조명이 아름다워요. 저녁에 방문도 추천!", dislikeFlags: [] },
  { name: "전주 한옥마을", emoji: "🏠", region: "국내", country: "대한민국", description: "전통과 현대가 어우러진 한옥 체험", bestSeasons: ["봄", "가을", "겨울"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["문화탐방", "맛집투어", "쇼핑"], companions: ["연인", "친구", "가족(아이)", "혼자", "부모님"], highlights: ["한복 체험", "초코파이 만들기", "전동성당", "막걸리 골목"], tip: "주말에는 사람이 많으니 평일 방문을 추천해요.", dislikeFlags: [] },
  { name: "삼척", emoji: "🌊", region: "국내", country: "대한민국", description: "해신당공원과 대금굴의 도시", bestSeasons: ["여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "문화탐방", "힐링"], companions: ["친구", "연인", "가족(아이)"], highlights: ["해신당공원", "대금굴", "이사부 사자공원", "장호어촌체험마을"], tip: "대금굴은 모노레일을 타고 들어가는 독특한 동굴! 사전 예약 필수.", dislikeFlags: ["바다"] },
  { name: "울산", emoji: "🐋", region: "국내", country: "대한민국", description: "고래의 도시, 대왕암과 간절곶", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "문화탐방", "맛집투어"], companions: ["연인", "가족(아이)", "친구", "혼자"], highlights: ["대왕암공원", "간절곶 일출", "장생포 고래박물관", "태화강 십리대숲"], tip: "간절곶은 한반도에서 가장 먼저 해가 뜨는 곳이에요!", dislikeFlags: ["바다"] },
  { name: "서산", emoji: "🌅", region: "국내", country: "대한민국", description: "서해안 일몰 명소와 해미읍성", bestSeasons: ["가을", "겨울"], durations: ["1박2일"], budgetLevel: 1, styles: ["문화탐방", "자연", "힐링"], companions: ["부모님", "연인", "혼자"], highlights: ["해미읍성", "천수만 철새도래지", "가야산", "서산 마애삼존불상"], tip: "겨울 천수만에서 철새 관찰이 특별한 경험이에요.", dislikeFlags: [] },
  { name: "제천", emoji: "🎶", region: "국내", country: "대한민국", description: "의림지와 청풍호의 도시", bestSeasons: ["여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "힐링", "액티비티"], companions: ["연인", "친구", "가족(아이)"], highlights: ["의림지", "청풍호 유람선", "월악산", "제천 국제음악영화제"], tip: "청풍호 유람선에서 보는 풍경이 그림 같아요!", dislikeFlags: [] },
  { name: "보성", emoji: "🍵", region: "국내", country: "대한민국", description: "녹차밭이 아름다운 차의 고장", bestSeasons: ["봄", "여름"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["자연", "힐링", "맛집투어"], companions: ["연인", "부모님", "혼자", "친구"], highlights: ["대한다원 녹차밭", "벌교 꼬막", "율포해수녹차탕", "봇재 전망대"], tip: "초록빛 녹차밭 사진을 남기려면 5~6월이 가장 좋아요.", dislikeFlags: [] },
  { name: "영덕", emoji: "🦀", region: "국내", country: "대한민국", description: "대게의 고장, 블루로드 트레킹", bestSeasons: ["겨울", "봄"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["맛집투어", "자연", "힐링"], companions: ["부모님", "친구", "연인"], highlights: ["영덕 대게", "블루로드", "풍력발전단지", "강구항"], tip: "11월~3월이 대게 시즌! 강구항에서 싱싱한 대게를 드세요.", dislikeFlags: ["바다"] },
  { name: "완도", emoji: "🌊", region: "국내", country: "대한민국", description: "청정 바다와 전복의 섬", bestSeasons: ["봄", "여름"], durations: ["2박3일"], budgetLevel: 2, styles: ["자연", "힐링", "맛집투어"], companions: ["부모님", "연인", "친구"], highlights: ["보길도 세연정", "완도타워", "전복요리", "정도리 구계등"], tip: "완도 전복은 다른 곳과 차원이 다릅니다. 전복죽, 전복회 꼭 드세요!", dislikeFlags: ["바다"] },
  { name: "고성", emoji: "🦕", region: "국내", country: "대한민국", description: "공룡발자국과 상족암의 도시", bestSeasons: ["봄", "여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "문화탐방", "액티비티"], companions: ["가족(아이)", "친구", "연인"], highlights: ["상족암 공룡발자국", "당항포 관광지", "고성 공룡박물관", "해안 둘레길"], tip: "아이와 함께라면 공룡박물관은 필수 코스!", dislikeFlags: ["바다"] },
  { name: "홍천", emoji: "🌳", region: "국내", country: "대한민국", description: "비발디파크와 자연 속 힐링", bestSeasons: ["여름", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["액티비티", "자연", "힐링"], companions: ["가족(아이)", "친구", "연인"], highlights: ["비발디파크", "수타사", "은행나무숲", "홍천강"], tip: "여름에는 수상레저, 겨울에는 스키로 사계절 즐길 수 있어요.", dislikeFlags: [] },
  { name: "무주", emoji: "🦋", region: "국내", country: "대한민국", description: "반딧불이와 무주리조트의 청정지역", bestSeasons: ["여름", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "액티비티", "힐링"], companions: ["가족(아이)", "친구", "연인"], highlights: ["무주리조트 스키장", "반디랜드", "덕유산 향적봉", "구천동 33경"], tip: "여름 반딧불이 축제가 정말 환상적이에요!", dislikeFlags: [] },
  { name: "진안", emoji: "🏔️", region: "국내", country: "대한민국", description: "마이산과 운장산의 자연 속 힐링", bestSeasons: ["봄", "가을", "겨울"], durations: ["1박2일"], budgetLevel: 1, styles: ["자연", "힐링"], companions: ["연인", "혼자", "부모님"], highlights: ["마이산 탑사", "운장산", "데미샘 쉼터", "홍삼 스파"], tip: "마이산 겨울 역고드름은 신비로운 자연현상이에요!", dislikeFlags: ["등산"] },
  { name: "해남", emoji: "🌏", region: "국내", country: "대한민국", description: "한반도 최남단 땅끝마을", bestSeasons: ["봄", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "문화탐방", "힐링"], companions: ["부모님", "연인", "혼자"], highlights: ["땅끝마을 전망대", "대흥사", "두륜산", "해남 배추김치"], tip: "땅끝마을에서 보는 일몰이 정말 감동적이에요.", dislikeFlags: [] },
  { name: "양평", emoji: "🚲", region: "국내", country: "대한민국", description: "두물머리와 자전거길의 근교 여행지", bestSeasons: ["봄", "여름", "가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["자연", "힐링", "액티비티"], companions: ["연인", "가족(아이)", "친구", "혼자"], highlights: ["두물머리", "세미원", "양평 자전거길", "용문사 은행나무"], tip: "두물머리 새벽 물안개가 장관이에요. 자전거 대여로 즐기면 좋아요.", dislikeFlags: [] },
  { name: "의성", emoji: "🧄", region: "국내", country: "대한민국", description: "마늘의 고장과 빙계계곡", bestSeasons: ["여름", "가을"], durations: ["1박2일"], budgetLevel: 1, styles: ["자연", "힐링"], companions: ["부모님", "연인", "혼자"], highlights: ["빙계계곡", "조문국 사적지", "의성 마늘축제", "만취당"], tip: "여름 빙계계곡의 얼음물이 정말 시원해요.", dislikeFlags: [] },
  { name: "논산", emoji: "🍓", region: "국내", country: "대한민국", description: "딸기의 고장과 관촉사 은진미륵", bestSeasons: ["봄", "겨울"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["문화탐방", "맛집투어"], companions: ["가족(아이)", "부모님", "연인"], highlights: ["관촉사 은진미륵", "논산 딸기축제", "연산역", "탑정호"], tip: "12월~2월 딸기 수확 체험이 아이들에게 인기!", dislikeFlags: [] },
  { name: "횡성", emoji: "🐄", region: "국내", country: "대한민국", description: "한우의 고장, 청정 자연 속 미식 여행", bestSeasons: ["가을", "겨울"], durations: ["1박2일"], budgetLevel: 2, styles: ["맛집투어", "자연", "힐링"], companions: ["연인", "친구", "부모님"], highlights: ["횡성 한우", "청태산 자연휴양림", "풍수원성당", "회동리 해바라기축제"], tip: "횡성 한우축제(10월)에 가면 시세보다 저렴하게 한우를 즐길 수 있어요.", dislikeFlags: [] },
  { name: "영양", emoji: "🌌", region: "국내", country: "대한민국", description: "반딧불이와 별빛의 청정지역", bestSeasons: ["여름", "가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "힐링"], companions: ["연인", "혼자", "친구"], highlights: ["자생화공원", "반딧불이 생태공원", "선바위 관광지", "두들마을"], tip: "국제밤하늘보호공원으로 지정된 곳! 별 관측에 최적이에요.", dislikeFlags: [] },
  { name: "청송", emoji: "🍎", region: "국내", country: "대한민국", description: "주왕산과 사과의 고장", bestSeasons: ["가을"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "힐링", "액티비티"], companions: ["친구", "연인", "혼자"], highlights: ["주왕산", "주산지", "청송 사과축제", "얼음골"], tip: "주산지 새벽 물안개 사진이 유명해요. 이른 아침에 방문하세요!", dislikeFlags: ["등산"] },
  { name: "태백", emoji: "⛏️", region: "국내", country: "대한민국", description: "태백산과 탄광역사의 도시", bestSeasons: ["여름", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 2, styles: ["자연", "문화탐방", "액티비티"], companions: ["친구", "연인", "가족(아이)"], highlights: ["태백산", "태백 석탄박물관", "구문소", "365 세이프타운"], tip: "여름에도 서늘한 기후로 피서지로 좋아요. 겨울 눈꽃축제도 유명!", dislikeFlags: ["등산"] },
  { name: "상주", emoji: "🚴", region: "국내", country: "대한민국", description: "자전거의 도시, 곶감과 경천대", bestSeasons: ["가을"], durations: ["당일치기", "1박2일"], budgetLevel: 1, styles: ["자연", "힐링", "액티비티"], companions: ["연인", "친구", "혼자"], highlights: ["경천대", "낙동강 자전거길", "상주 곶감", "경천섬"], tip: "낙동강 자전거길의 시작점! 자전거 라이딩 코스로 최고에요.", dislikeFlags: [] },
  { name: "봉화", emoji: "🍂", region: "국내", country: "대한민국", description: "송이버섯과 청량산의 청정지역", bestSeasons: ["가을"], durations: ["1박2일"], budgetLevel: 2, styles: ["자연", "맛집투어", "힐링"], companions: ["부모님", "연인", "혼자"], highlights: ["청량산", "봉화 송이축제", "춘양목 군락지", "만산고택"], tip: "가을 송이축제 때 싱싱한 송이버섯 요리를 맛보세요!", dislikeFlags: ["등산"] },

  // ═══ 해외 가까운 (22) ═══
  { name: "오사카", emoji: "🏯", region: "해외(가까운)", country: "일본", description: "먹거리와 즐길거리가 넘치는 일본 제2의 도시", bestSeasons: ["봄", "가을"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["맛집투어", "쇼핑", "문화탐방"], companions: ["친구", "연인", "가족(아이)", "혼자"], highlights: ["도톤보리", "오사카성", "유니버설 스튜디오", "쿠로몬 시장"], tip: "교통패스(오사카 주유패스)를 사면 교통비와 입장료를 절약할 수 있어요.", dislikeFlags: ["비행기"] },
  { name: "도쿄", emoji: "🗼", region: "해외(가까운)", country: "일본", description: "전통과 현대가 공존하는 세계 최대 도시", bestSeasons: ["봄", "가을", "겨울"], durations: ["2박3일", "일주일 이상"], budgetLevel: 4, styles: ["쇼핑", "문화탐방", "맛집투어", "액티비티"], companions: ["친구", "연인", "혼자", "가족(아이)"], highlights: ["시부야 스크램블", "아사쿠사 센소지", "아키하바라", "디즈니랜드"], tip: "스이카 교통카드 하나면 어디든 편하게 이동할 수 있어요.", dislikeFlags: ["비행기"] },
  { name: "후쿠오카", emoji: "🍜", region: "해외(가까운)", country: "일본", description: "돈코츠 라멘의 본고장, 부산에서 가장 가까운 일본", bestSeasons: ["봄", "가을", "겨울"], durations: ["1박2일", "2박3일"], budgetLevel: 3, styles: ["맛집투어", "쇼핑", "힐링"], companions: ["연인", "친구", "혼자", "부모님"], highlights: ["하카타 라멘", "캐널시티", "다자이후 텐만구", "야타이 포장마차"], tip: "부산에서 배로도 갈 수 있어요! 야타이(포장마차) 라멘은 꼭 드세요.", dislikeFlags: ["비행기"] },
  { name: "교토", emoji: "⛩️", region: "해외(가까운)", country: "일본", description: "천년 고도, 일본 전통문화의 중심", bestSeasons: ["봄", "가을"], durations: ["2박3일", "일주일 이상"], budgetLevel: 4, styles: ["문화탐방", "힐링", "맛집투어"], companions: ["연인", "혼자", "부모님", "친구"], highlights: ["후시미이나리", "금각사", "아라시야마 대나무숲", "기온 게이샤거리"], tip: "오사카에서 전철로 30분! 오사카 숙소에서 당일치기로도 가능해요.", dislikeFlags: ["비행기"] },
  { name: "방콕", emoji: "🛕", region: "해외(가까운)", country: "태국", description: "화려한 사원과 길거리 음식의 천국", bestSeasons: ["겨울", "봄"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["맛집투어", "쇼핑", "문화탐방", "힐링"], companions: ["친구", "연인", "혼자"], highlights: ["왓 프라깨오", "카오산로드", "짜뚜짝 시장", "태국 마사지"], tip: "11월~2월 건기 시즌이 여행하기 가장 좋아요. 물가가 저렴해서 가성비 최고!", dislikeFlags: ["비행기", "더위"] },
  { name: "다낭", emoji: "🏖️", region: "해외(가까운)", country: "베트남", description: "아름다운 해변과 바나힐의 베트남 휴양도시", bestSeasons: ["봄", "겨울"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["힐링", "맛집투어", "액티비티", "자연"], companions: ["연인", "친구", "가족(아이)", "혼자"], highlights: ["미케비치", "바나힐 골든브릿지", "호이안 올드타운", "마블마운틴"], tip: "호이안까지 택시로 40분! 다낭+호이안 묶어서 여행하면 좋아요.", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "타이베이", emoji: "🧋", region: "해외(가까운)", country: "대만", description: "야시장과 버블티의 나라, 친절한 사람들", bestSeasons: ["봄", "가을", "겨울"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["맛집투어", "쇼핑", "문화탐방"], companions: ["친구", "연인", "혼자", "가족(아이)"], highlights: ["스린 야시장", "지우펀", "타이베이 101", "딘타이펑 딤섬"], tip: "이지카드(교통카드)를 공항에서 바로 사면 편리해요. 야시장 꼭 가세요!", dislikeFlags: ["비행기"] },
  { name: "홍콩", emoji: "🌃", region: "해외(가까운)", country: "홍콩", description: "빅토리아 하버 야경과 딤섬의 도시", bestSeasons: ["가을", "겨울"], durations: ["2박3일"], budgetLevel: 4, styles: ["쇼핑", "맛집투어", "문화탐방"], companions: ["연인", "친구", "혼자"], highlights: ["빅토리아 피크", "심포니 오브 라이트", "딤섬", "란콰이펑"], tip: "옥토퍼스 카드 하나면 교통+편의점+음식점 결제가 가능해요.", dislikeFlags: ["비행기"] },
  { name: "싱가포르", emoji: "🦁", region: "해외(가까운)", country: "싱가포르", description: "미래도시와 다문화 음식의 나라", bestSeasons: ["봄", "가을", "겨울"], durations: ["2박3일", "일주일 이상"], budgetLevel: 4, styles: ["쇼핑", "맛집투어", "문화탐방", "액티비티"], companions: ["연인", "가족(아이)", "친구", "혼자"], highlights: ["마리나 베이 샌즈", "가든스 바이 더 베이", "센토사 섬", "칠리크랩"], tip: "호커센터(푸드코트)에서 저렴하게 맛있는 음식을 즐길 수 있어요.", dislikeFlags: ["비행기", "더위"] },
  { name: "세부", emoji: "🐋", region: "해외(가까운)", country: "필리핀", description: "고래상어 투어와 아름다운 해변의 섬", bestSeasons: ["겨울", "봄"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["액티비티", "힐링", "자연"], companions: ["연인", "친구", "혼자"], highlights: ["고래상어 스노클링", "가와산 캐녀닝", "나루수안 섬", "망고"], tip: "오슬롭 고래상어 투어는 새벽에 출발해야 해요. 숙소를 근처에 잡으세요.", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "보라카이", emoji: "🏝️", region: "해외(가까운)", country: "필리핀", description: "세계 최고의 화이트 비치", bestSeasons: ["겨울", "봄"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["힐링", "액티비티", "자연"], companions: ["연인", "친구", "가족(아이)"], highlights: ["화이트비치", "파라세일링", "아일랜드 호핑", "선셋 세일링"], tip: "건기(11월~5월)에 가면 맑은 하늘과 투명한 바다를 즐길 수 있어요.", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "발리", emoji: "🌺", region: "해외(가까운)", country: "인도네시아", description: "신들의 섬, 서핑과 요가의 천국", bestSeasons: ["봄", "여름", "가을"], durations: ["일주일 이상"], budgetLevel: 3, styles: ["힐링", "자연", "문화탐방", "액티비티"], companions: ["연인", "친구", "혼자"], highlights: ["우붓 라이스테라스", "울루와뚜 사원", "스미냑 비치", "발리 스윙"], tip: "4~10월 건기 시즌이 여행 적기. 우붓에서 문화체험, 쿠타에서 서핑을 즐기세요.", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "괌", emoji: "🌴", region: "해외(가까운)", country: "미국령", description: "한국에서 가장 가까운 미국, 면세 쇼핑 천국", bestSeasons: ["겨울", "봄"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["힐링", "쇼핑", "액티비티", "자연"], companions: ["가족(아이)", "연인", "친구"], highlights: ["투몬비치", "GPO 쇼핑몰", "사랑의 절벽", "스노클링"], tip: "비행시간 4시간 반! 면세 한도를 활용한 쇼핑이 인기에요.", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "사이판", emoji: "🏖️", region: "해외(가까운)", country: "미국령", description: "에메랄드빛 바다와 만세절벽의 섬", bestSeasons: ["겨울", "봄"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["힐링", "자연", "액티비티"], companions: ["가족(아이)", "연인", "친구"], highlights: ["마나가하 섬", "만세절벽", "그로토 스노클링", "마이크로비치"], tip: "마나가하 섬 반일투어가 인기! 수영 못 해도 스노클링 가능해요.", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "나트랑", emoji: "🏄", region: "해외(가까운)", country: "베트남", description: "베트남의 리조트 도시, 머드 스파와 해변", bestSeasons: ["봄", "겨울"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["힐링", "액티비티", "맛집투어"], companions: ["연인", "친구", "가족(아이)"], highlights: ["빈펄랜드", "머드 스파", "호핑투어", "반미·쌀국수"], tip: "물가가 매우 저렴해서 리조트 호캉스에 최적이에요!", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "치앙마이", emoji: "🐘", region: "해외(가까운)", country: "태국", description: "태국 북부의 문화도시, 코끼리와 사원", bestSeasons: ["겨울", "봄"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["문화탐방", "힐링", "맛집투어", "자연"], companions: ["혼자", "연인", "친구"], highlights: ["왓 프라탓 도이수텝", "코끼리 보호소", "야시장", "카오소이"], tip: "11~2월이 가장 쾌적해요. 디지털 노마드에게도 인기 있는 도시!", dislikeFlags: ["비행기", "더위"] },
  { name: "푸꾸옥", emoji: "🌅", region: "해외(가까운)", country: "베트남", description: "베트남 최남단 섬, 선셋과 리조트", bestSeasons: ["겨울", "봄"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["힐링", "자연", "맛집투어"], companions: ["연인", "가족(아이)", "친구"], highlights: ["선셋타운", "호핑투어", "빈원더스", "해산물 야시장"], tip: "11~3월 건기가 여행 적기. 선셋타운의 키스브릿지 노을이 환상적!", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "코타키나발루", emoji: "🏔️", region: "해외(가까운)", country: "말레이시아", description: "키나발루산과 아름다운 노을의 도시", bestSeasons: ["봄", "여름"], durations: ["2박3일", "일주일 이상"], budgetLevel: 3, styles: ["자연", "힐링", "액티비티"], companions: ["연인", "친구", "가족(아이)"], highlights: ["키나발루산", "세계 3대 노을", "호핑투어", "필리피노 마켓"], tip: "노을이 정말 아름다워서 '세계 3대 석양'으로 불려요.", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "호이안", emoji: "🏮", region: "해외(가까운)", country: "베트남", description: "등불의 도시, 유네스코 세계문화유산", bestSeasons: ["봄", "겨울"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["연인", "혼자", "친구", "부모님"], highlights: ["올드타운 야경", "등불 축제", "바인미·까오러우", "맞춤 옷 제작"], tip: "매달 음력 14일 등불축제가 가장 아름다워요. 맞춤 옷은 24시간이면 완성!", dislikeFlags: ["비행기", "더위"] },
  { name: "하노이", emoji: "🍜", region: "해외(가까운)", country: "베트남", description: "천년 고도, 쌀국수와 프렌치 건축의 도시", bestSeasons: ["봄", "가을", "겨울"], durations: ["2박3일", "일주일 이상"], budgetLevel: 2, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["친구", "연인", "혼자"], highlights: ["호안끼엠호수", "하롱베이 투어", "기찻길 마을", "분짜·에그커피"], tip: "하롱베이 1박2일 크루즈 투어를 강력 추천! 물가가 정말 저렴해요.", dislikeFlags: ["비행기"] },

  // ═══ 해외 먼 (20) ═══
  { name: "파리", emoji: "🗼", region: "해외(먼)", country: "프랑스", description: "에펠탑과 루브르, 세계 예술과 패션의 수도", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["문화탐방", "쇼핑", "맛집투어", "힐링"], companions: ["연인", "친구", "혼자", "부모님"], highlights: ["에펠탑", "루브르 박물관", "몽마르트르", "세느강 유람선"], tip: "뮤지엄 패스를 구매하면 주요 박물관을 줄 서지 않고 입장할 수 있어요.", dislikeFlags: ["비행기"] },
  { name: "런던", emoji: "🎡", region: "해외(먼)", country: "영국", description: "빅벤과 대영박물관, 전통과 트렌드의 도시", bestSeasons: ["봄", "여름"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["문화탐방", "쇼핑", "맛집투어"], companions: ["친구", "연인", "혼자"], highlights: ["대영박물관", "빅벤", "타워브릿지", "웨스트엔드 뮤지컬"], tip: "대영박물관은 무료입장! 오이스터 카드로 교통비를 절약하세요.", dislikeFlags: ["비행기"] },
  { name: "로마", emoji: "🏛️", region: "해외(먼)", country: "이탈리아", description: "콜로세움과 바티칸, 모든 길이 통하는 도시", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["연인", "친구", "혼자", "부모님"], highlights: ["콜로세움", "바티칸 박물관", "트레비 분수", "젤라또·파스타"], tip: "바티칸 박물관은 온라인 사전 예약 필수! 소매치기 조심하세요.", dislikeFlags: ["비행기"] },
  { name: "바르셀로나", emoji: "🎭", region: "해외(먼)", country: "스페인", description: "가우디의 건축과 지중해의 해변 도시", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["문화탐방", "맛집투어", "힐링", "쇼핑"], companions: ["연인", "친구", "혼자"], highlights: ["사그라다 파밀리아", "구엘공원", "람블라스 거리", "타파스·빠에야"], tip: "사그라다 파밀리아는 반드시 온라인 예약! 주요 관광지 근처에서 소매치기 주의.", dislikeFlags: ["비행기"] },
  { name: "프라하", emoji: "🏰", region: "해외(먼)", country: "체코", description: "동화 속 중세도시, 맥주와 야경의 도시", bestSeasons: ["봄", "가을", "겨울"], durations: ["일주일 이상"], budgetLevel: 4, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["연인", "친구", "혼자"], highlights: ["프라하성", "카를교", "구시가지 광장", "체코 맥주·뜨르들로"], tip: "유럽 중에서 물가가 저렴한 편! 야경이 특히 아름다운 도시에요.", dislikeFlags: ["비행기"] },
  { name: "뉴욕", emoji: "🗽", region: "해외(먼)", country: "미국", description: "자유의 여신상과 브로드웨이, 세계의 수도", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["문화탐방", "쇼핑", "맛집투어", "액티비티"], companions: ["친구", "연인", "혼자"], highlights: ["타임스 스퀘어", "센트럴파크", "브로드웨이 뮤지컬", "자유의 여신상"], tip: "시티패스를 구매하면 주요 관광지 입장료를 40%이상 절약할 수 있어요.", dislikeFlags: ["비행기"] },
  { name: "LA", emoji: "🎬", region: "해외(먼)", country: "미국", description: "할리우드와 산타모니카 비치의 도시", bestSeasons: ["봄", "여름", "가을"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["쇼핑", "액티비티", "문화탐방", "맛집투어"], companions: ["친구", "연인", "가족(아이)"], highlights: ["할리우드", "산타모니카 비치", "유니버설 스튜디오", "그리피스 천문대"], tip: "렌터카가 거의 필수! 교통체증을 피해 아침 일찍 움직이세요.", dislikeFlags: ["비행기", "바다"] },
  { name: "하와이", emoji: "🌺", region: "해외(먼)", country: "미국", description: "세계적인 리조트와 화산섬의 천국", bestSeasons: ["봄", "여름", "가을", "겨울"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["힐링", "자연", "액티비티", "쇼핑"], companions: ["연인", "가족(아이)", "친구", "부모님"], highlights: ["와이키키 비치", "다이아몬드 헤드", "할레아칼라 일출", "루아우 쇼"], tip: "오아후 섬이 가장 대중적이고, 마우이 섬은 자연이 더 아름다워요.", dislikeFlags: ["비행기", "바다"] },
  { name: "시드니", emoji: "🦘", region: "해외(먼)", country: "호주", description: "오페라하우스와 하버브릿지의 도시", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["문화탐방", "자연", "액티비티", "맛집투어"], companions: ["친구", "연인", "혼자", "가족(아이)"], highlights: ["오페라하우스", "하버브릿지", "본다이 비치", "블루마운틴"], tip: "한국과 계절이 반대! 한국 겨울에 가면 호주 여름을 즐길 수 있어요.", dislikeFlags: ["비행기", "바다"] },
  { name: "스위스(인터라켄)", emoji: "🏔️", region: "해외(먼)", country: "스위스", description: "알프스의 심장, 융프라우와 호수의 나라", bestSeasons: ["여름", "겨울"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["자연", "액티비티", "힐링"], companions: ["연인", "친구", "가족(아이)", "부모님"], highlights: ["융프라우", "그린델발트", "인터라켄 패러글라이딩", "루체른 호수"], tip: "스위스 트래블 패스로 기차·버스·유람선을 무제한 이용할 수 있어요.", dislikeFlags: ["비행기"] },
  { name: "크로아티아(두브로브니크)", emoji: "🏰", region: "해외(먼)", country: "크로아티아", description: "왕좌의 게임 촬영지, 아드리아 해의 보석", bestSeasons: ["봄", "여름", "가을"], durations: ["일주일 이상"], budgetLevel: 4, styles: ["문화탐방", "힐링", "자연"], companions: ["연인", "친구", "혼자"], highlights: ["올드타운 성벽", "스르지산 케이블카", "카약 투어", "플리트비체 호수"], tip: "성수기(7~8월)에는 매우 붐비니 5~6월이나 9~10월을 추천해요.", dislikeFlags: ["비행기", "바다"] },
  { name: "이스탄불", emoji: "🕌", region: "해외(먼)", country: "튀르키예", description: "동서양이 만나는 도시, 모스크와 바자르", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 3, styles: ["문화탐방", "맛집투어", "쇼핑"], companions: ["친구", "연인", "혼자"], highlights: ["아야소피아", "블루 모스크", "그랜드 바자르", "케밥·바클라바"], tip: "이스탄불 카드(교통카드)를 공항에서 사면 편리해요. 카파도키아도 같이 여행하세요!", dislikeFlags: ["비행기"] },
  { name: "리스본", emoji: "🚋", region: "해외(먼)", country: "포르투갈", description: "트램과 파스텔 드 나타의 인스타그램 도시", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 4, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["연인", "친구", "혼자"], highlights: ["벨렘탑", "28번 트램", "제로니무스 수도원", "에그타르트"], tip: "포르투갈 물가는 유럽 중 저렴한 편. 에그타르트 원조인 파스텔 드 벨렘 꼭 가세요!", dislikeFlags: ["비행기"] },
  { name: "빈", emoji: "🎵", region: "해외(먼)", country: "오스트리아", description: "모차르트와 슈니첼, 음악의 도시", bestSeasons: ["봄", "가을", "겨울"], durations: ["일주일 이상"], budgetLevel: 4, styles: ["문화탐방", "맛집투어", "힐링"], companions: ["연인", "부모님", "혼자", "친구"], highlights: ["쇤브룬 궁전", "빈 오페라하우스", "슈니첼·자허토르테", "나슈마르크트"], tip: "빈 카드를 사면 대중교통 무제한+박물관 할인을 받을 수 있어요.", dislikeFlags: ["비행기"] },
  { name: "암스테르담", emoji: "🌷", region: "해외(먼)", country: "네덜란드", description: "운하와 자전거, 튤립과 고흐의 도시", bestSeasons: ["봄", "여름"], durations: ["일주일 이상"], budgetLevel: 4, styles: ["문화탐방", "힐링", "자연"], companions: ["연인", "친구", "혼자"], highlights: ["반 고흐 미술관", "안네 프랑크의 집", "운하 크루즈", "큐켄호프 튤립 축제"], tip: "4~5월 튤립 시즌에 방문하면 큐켄호프 정원이 장관이에요!", dislikeFlags: ["비행기"] },
  { name: "뮌헨", emoji: "🍺", region: "해외(먼)", country: "독일", description: "맥주 축제와 바이에른 문화의 중심", bestSeasons: ["여름", "가을"], durations: ["일주일 이상"], budgetLevel: 4, styles: ["맛집투어", "문화탐방", "쇼핑"], companions: ["친구", "연인", "혼자"], highlights: ["마리엔 광장", "옥토버페스트", "노이슈반슈타인 성", "맥주 홀"], tip: "옥토버페스트(9~10월)는 세계 최대 맥주축제! 일찍 가서 자리를 잡으세요.", dislikeFlags: ["비행기"] },
  { name: "모로코(마라케시)", emoji: "🏜️", region: "해외(먼)", country: "모로코", description: "사하라 사막과 이국적인 메디나의 나라", bestSeasons: ["봄", "가을"], durations: ["일주일 이상"], budgetLevel: 3, styles: ["문화탐방", "자연", "액티비티"], companions: ["친구", "연인", "혼자"], highlights: ["사하라 사막투어", "메디나 시장", "마조렐 정원", "모로코 민트티"], tip: "사하라 사막 1박 투어는 별이 쏟아지는 잊지 못할 경험이에요.", dislikeFlags: ["비행기", "더위"] },
  { name: "멕시코(칸쿤)", emoji: "🌮", region: "해외(먼)", country: "멕시코", description: "카리브해 리조트와 마야 유적의 도시", bestSeasons: ["겨울", "봄"], durations: ["일주일 이상"], budgetLevel: 4, styles: ["힐링", "액티비티", "문화탐방", "자연"], companions: ["연인", "친구", "가족(아이)"], highlights: ["카리브해 해변", "치첸이트사", "세노테 수영", "타코·과카몰레"], tip: "올인클루시브 리조트에서 편하게 쉬거나, 치첸이트사 데이투어를 추천!", dislikeFlags: ["비행기", "더위", "바다"] },
  { name: "아이슬란드(레이캬비크)", emoji: "🌋", region: "해외(먼)", country: "아이슬란드", description: "오로라와 빙하, 지구 밖 같은 풍경의 나라", bestSeasons: ["여름", "겨울"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["자연", "액티비티", "힐링"], companions: ["연인", "친구", "혼자"], highlights: ["오로라", "골든서클", "블루라군", "빙하 하이킹"], tip: "겨울에는 오로라, 여름에는 백야를 경험할 수 있어요. 렌터카로 링로드 일주 추천!", dislikeFlags: ["비행기", "추위"] },
  { name: "뉴질랜드(퀸스타운)", emoji: "🏞️", region: "해외(먼)", country: "뉴질랜드", description: "번지점프의 성지, 밀포드사운드의 대자연", bestSeasons: ["봄", "여름"], durations: ["일주일 이상"], budgetLevel: 5, styles: ["자연", "액티비티", "힐링"], companions: ["연인", "친구", "혼자"], highlights: ["밀포드사운드", "번지점프", "스카이다이빙", "반지의 제왕 촬영지"], tip: "한국과 계절이 반대! 남섬 중심으로 여행하면 대자연을 만끽할 수 있어요.", dislikeFlags: ["비행기"] },
];

export const DESTINATIONS = D;
